### ISSUE TITLE
Complete parsing Xtext

### ISSUE THREAD

**Issue by martijndwars** [MartijnDwars/Xtext#1]
Currently Xtext is partially parsed, but this needs to be completed. See the [https://github.com/eclipse/xtext/blob/v2.8.0/plugins/org.eclipse.xtext/src/org/eclipse/xtext/Xtext.xtext](https://github.com/eclipse/xtext/blob/v2.8.0/plugins/org.eclipse.xtext/src/org/eclipse/xtext/Xtext.xtext) (Xtext grammar in Xtext) for a full list. Some things that need to be looked at:
- [x] `definesHiddenTokens` on Grammar (Binni)
- [x] `definesHiddenTokens` on ParserRule (Binni)
- [x] TypeRef with AbstractMetamodelDeclaration (Jeff, this I am not confident about, assumed the metamodel-reference was a STRING as well)
- [x] AbstractTerminal is still missing PredicatedKeyword, PredicatedRuleCall, PredicatedGroup (Jeff)
- [x] Assignment is missing predicates (Jeff)
- [x] ParenthesizedAssignableElement and ParenthesizedElement should not have a constructor (like in MiniJava) (Needs to be looked into)
- [x] TerminalRule is missing fragments (Jeff)
- [x] TerminalTokenElement is missing RuleCall, ParenthesizedTerminalElement, AbstractNegatedToken (Jeff)
- [x] ParenthesizedTerminalElement(Jeff)
- [x] AbstractNegatedToken (Jeff, omitted due to abstraction, will explain)
- [x] NegatedToken (Jeff)
- [x] UntilToken (Jeff)

**Comment by JeffGoderie** [comment]
@MartijnDwars What do you mean by "ParenthesizedAssignableElement and ParenthesizedElement should not have a constructor (like in MiniJava)"?

**Comment by martijndwars** [comment]
Oh that was mostly a note to self. IIRC, we currently introduce a constructor for this symbol. However, since the parentheses do not convey any meaning (semantically) we should not use a constructor. I remember also using the `{bracket}` attribute in MiniJava.

**Comment by JeffGoderie** [comment]
Ah, like that, want me to just add it using a constructor for now?
