### ISSUE TITLE
Syntax limitations 

### ISSUE THREAD

**Issue by JeffGoderie** [MartijnDwars/Xtext#17]
The Xtext syntax allows more than that is allowed in a valid Xtext program. We should try and find these situations and try to either limit them in the syntax definition or using TS rules.

**Comment by binnimar** [comment]
Couple of things that are allowed in our project but shouldn't be according to XText workbench

```
// This shouldn't be allowed  
ActionsTest:
    {actionOne} ('x')
    {actionTwo} ('y')
;

AbstractElement:
  {pd} PackageDeclaration | Type | Import
;
```

**Comment by martijndwars** [comment]
@binnimar is this because we made a mistake in implementing the parser, or because Xtext adds additional constraints?

**Comment by binnimar** [comment]
@MartijnDwars  
I think it is because XText adds additional constraints but I still have to dive a little deeper into that subject
