### ISSUE TITLE
Quotation

### ISSUE THREAD

**Issue by martijndwars** [MartijnDwars/Xtext#27]
We are probably all aware of the problem, but I'm creating this issue to formally document it. Given the following Xtext:

```
BasicType : basic=('int' | 'boolean' | 'String');
```

we generate the following SDF:

```
BasicType.BasicType-197 = basic:BasicType-SubRule-197 
BasicType-SubRule-197 = "'int'" 
BasicType-SubRule-197 = "'boolean'" 
BasicType-SubRule-197 = "'String'"
```

whereas we expect the following SDF:

```
BasicType = 'int'
BasicType = 'boolean'
BasicType = 'String'
```

note the quotation.

**Comment by JeffGoderie** [comment]
I believe we have fixed this now, so I'm closing this issue
