### ISSUE TITLE
CrossReferene

### ISSUE THREAD

**Issue by JeffGoderie** [MartijnDwars/Xtext#38]
For the CrossReferences we should collect all CrossReferences before conversion, generate the appropriate subrules (to avoid having multiple copies of one rule):

`[Parameter | INT] -> Parameter_Ref.Parameter_Ref = INT`
`[Temporary] -> Temporary_Ref.Temporary_Ref = ID`

then on final conversion every CrossReference can be turned into:

`Rule := Optional_elements* [Rulename | Optional] Optional_elements* ->  Rule.Rule = Optional_elements* Rulename_Ref Optional_elements*`

**Comment by binnimar** [comment]
All done :+1:
