### ISSUE TITLE
Generating Arithmetic and FJ

### ISSUE THREAD

**Issue by JeffGoderie** [MartijnDwars/Xtext#5]
While going over the arithmetic file and the FJ file I found multiple elements that still need to be looked into:
- [x] Multiple UnorderedGroups in a single Alternative (@JeffGoderie)
- [x] Multiple Groups in a single UnorderedGroup (@JeffGoderie)
- [x] Multiple Alternatives in a Group (@MartijnDwars)
- [x] Actions (@binnimar)
- [x] ActionCurrent (@binnimar)
- [x] CrossReference
- [x] AssignableAlternatives
- [x] Get rid of ParenthesizedAssignableElement (as with ParenthesizedAlternatives) (@MartijnDwars)
- [x] TerminalRule (@MartijnDwars)
- [x] EnumRule (@MartijnDwars)

Also:
- [ ] We now assumed that assignment is one standard output, however this depends on the operator. If it is an addassignment() (=+) we need to output a list creation! (@JeffGoderie)
- [ ] See what hidden elements do, and if they are of value in Spoofax (@binnimar)
- [ ] See what predicated elements do, and if they are of value in Spoofax (@binnimar)
- [ ] As with the =+, see whether the =? has a specific, preferably clean version in Spoofax
- [ ] Think of some way to handle `CrossReference` and `RuleCall` in Spoofax.

Syntax:
- [ ] Adapt STRING rule to get rid of the comments
- [x] Parse comment blocks (@JeffGoderie, think I added this correctly, might require some more testing)
- [x] TerminalAlternatives needs alternatives (@JeffGoderie)
- [x] TerminalGroup needs Tokens (@JeffGoderie)

**Comment by JeffGoderie** [comment]
@MartijnDwars 
I don't know why you moved STRING to context-free syntax, but it now creates arrays of separate letters of each STRING occurence. This breaks Keyword among other things

**Comment by JeffGoderie** [comment]
As for the list generator, it's going to be rather messy at first, but I think it might be helpful to look into a cleaner solution after it has been created.

**Comment by martijndwars** [comment]
> I don't know why you moved STRING to context-free syntax

I wanted to remove the quotes from the string. We don't need them in the AST and we don't even want them in SDF (if we're using template syntax). But we should overcome those limitations you mentioned.

**Comment by JeffGoderie** [comment]
Ok, that makes sense.
For now I've reverted that change in my local branch, so that I can work on the other things first, but I'll add it to the issue list as well.

**Comment by binnimar** [comment]
Assigned myself a couple of issues before you guys finish everything - let me know if you have started working on this and I'll switch to something else

**Comment by JeffGoderie** [comment]
I claimed everything I was working on at this point, so go ahead.

**Comment by martijndwars** [comment]
Nope, go ahead :+1:

**Comment by martijndwars** [comment]
I have implemented some transformations for EnumRule and TerminalRule. They translate into lexical syntax in SDF. The SDF that is currently produced is a too verbose (e.g. character groups within character groups, such as `[[a]]`). I think it's easiest to prettify this in a post-processing phase (instead of complicating the parsing/transforming), but this requirers the SDF AST that Eduardo is working on.

**Comment by JeffGoderie** [comment]
Ok @MartijnDwars , when trying to merge my additions into yours, I got some merge conflicts. Turns out you implemented syntax definitions for some terminal rules as well, so I removed mine, and used yours, to avoid more problems.

**Comment by martijndwars** [comment]
Can you push your change @JeffGoderie? (Perhaps on a separate branch?)

**Comment by JeffGoderie** [comment]
Created a separate branch! Will be travelling tonight, so will be working on cleaning stuff up and trying to get the list generation done.

**Comment by JeffGoderie** [comment]
@MartijnDwars, @binnimar 
Hey guys, I'll not push my changes yet, but I'll give you a small update of what I've managed to do:

-permutations
-unordered groups and groups
-rulecalls
-cardinality around abstract-tokens

It currently looks really messy, so therefore I'll push them later. Eduardo managed to reserve the room for tomorrow, from 13.30 to 18.00.
