### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by martijndwars** [MartijnDwars/Xtext#6]
- [x] AssignableTerminalToken (@JeffGoderie)
- [x] ActionToken (@JeffGoderie)
- [x] Merge context-free sections/lexical syntax sections (during post-processing phase) (@MartijnDwars)
- [x] Output strings (@MartijnDwars)
- [x] CrossReference parsing (@Binnimar)

**Comment by JeffGoderie** [comment]
AssignableTerminalToken is done, including complicated list-structures (currently handled rather clumsy) with:

list = (list item) (tail item)*
tail-item = (separator) (list item)

This will need to be reformed to {(separator), (list item)}\* later on, but for now this will do. Will look into action tokens later this weekend.
