### ISSUE TITLE
Permutation Issue

### ISSUE THREAD

**Issue by JeffGoderie** [MartijnDwars/Xtext#9]
If a permutation list has an optional element, ambiguity will occur:

```
Model:
 static?='static'? & final?='final'? & visibility=Visibility
;
```

results in:

```
  Model = visibility:Visibility final:final? static:static? 
  Model = final:final? visibility:Visibility static:static? 
  Model = visibility:Visibility static:static? final:final? 
  Model = static:static? visibility:Visibility final:final? 
  Model = final:final? static:static? visibility:Visibility 
  Model = static:static? final:final? visibility:Visibility 
```

Possible solution would be to create permutations which create a version with and without the optional element. Another solution would be to create a list and have a validity check afterwards.

In both cases, we need to make sure that each version of the permutation results in the same AST.

**Comment by martijndwars** [comment]
It's not clear to me what you mean by validity check. How would such a validity check look like?

**Comment by JeffGoderie** [comment]
You will need to check whether the resulting list is valid with regard to
the xtext unordered group, so whether it contains the required elements.
What such a check would look like, I would not know, but Guido realised
this was one of the bigger problems.
Op 19 mei 2015 18:23 schreef "Martijn Dwars" notifications@github.com het
volgende:
